// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/itemsave/proto/item.proto

package api_trac_cn_saveitem

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	EpisodeId            int32    `protobuf:"varint,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	ChannelId            int32    `protobuf:"varint,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	DramaId              int32    `protobuf:"varint,3,opt,name=drama_id,json=dramaId,proto3" json:"drama_id,omitempty"`
	DramaTitle           string   `protobuf:"bytes,4,opt,name=drama_title,json=dramaTitle,proto3" json:"drama_title,omitempty"`
	Title1               string   `protobuf:"bytes,5,opt,name=title1,proto3" json:"title1,omitempty"`
	Title2               string   `protobuf:"bytes,6,opt,name=title2,proto3" json:"title2,omitempty"`
	Title3               string   `protobuf:"bytes,7,opt,name=title3,proto3" json:"title3,omitempty"`
	Title4               string   `protobuf:"bytes,8,opt,name=title4,proto3" json:"title4,omitempty"`
	EpisodeUrl           string   `protobuf:"bytes,9,opt,name=episode_url,json=episodeUrl,proto3" json:"episode_url,omitempty"`
	Duration             int32    `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`
	ContentType          string   `protobuf:"bytes,11,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Image                string   `protobuf:"bytes,12,opt,name=image,proto3" json:"image,omitempty"`
	IsIntact             string   `protobuf:"bytes,13,opt,name=is_intact,json=isIntact,proto3" json:"is_intact,omitempty"`
	IsNew                string   `protobuf:"bytes,14,opt,name=is_new,json=isNew,proto3" json:"is_new,omitempty"`
	IsVip                string   `protobuf:"bytes,15,opt,name=is_vip,json=isVip,proto3" json:"is_vip,omitempty"`
	PlayCounter          int64    `protobuf:"varint,16,opt,name=play_counter,json=playCounter,proto3" json:"play_counter,omitempty"`
	Ts                   string   `protobuf:"bytes,17,opt,name=ts,proto3" json:"ts,omitempty"`
	NextId               string   `protobuf:"bytes,18,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`
	SrcClipId            string   `protobuf:"bytes,19,opt,name=src_clip_id,json=srcClipId,proto3" json:"src_clip_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_7acdd0f2cbdcf63b, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetEpisodeId() int32 {
	if m != nil {
		return m.EpisodeId
	}
	return 0
}

func (m *Item) GetChannelId() int32 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *Item) GetDramaId() int32 {
	if m != nil {
		return m.DramaId
	}
	return 0
}

func (m *Item) GetDramaTitle() string {
	if m != nil {
		return m.DramaTitle
	}
	return ""
}

func (m *Item) GetTitle1() string {
	if m != nil {
		return m.Title1
	}
	return ""
}

func (m *Item) GetTitle2() string {
	if m != nil {
		return m.Title2
	}
	return ""
}

func (m *Item) GetTitle3() string {
	if m != nil {
		return m.Title3
	}
	return ""
}

func (m *Item) GetTitle4() string {
	if m != nil {
		return m.Title4
	}
	return ""
}

func (m *Item) GetEpisodeUrl() string {
	if m != nil {
		return m.EpisodeUrl
	}
	return ""
}

func (m *Item) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Item) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Item) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Item) GetIsIntact() string {
	if m != nil {
		return m.IsIntact
	}
	return ""
}

func (m *Item) GetIsNew() string {
	if m != nil {
		return m.IsNew
	}
	return ""
}

func (m *Item) GetIsVip() string {
	if m != nil {
		return m.IsVip
	}
	return ""
}

func (m *Item) GetPlayCounter() int64 {
	if m != nil {
		return m.PlayCounter
	}
	return 0
}

func (m *Item) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

func (m *Item) GetNextId() string {
	if m != nil {
		return m.NextId
	}
	return ""
}

func (m *Item) GetSrcClipId() string {
	if m != nil {
		return m.SrcClipId
	}
	return ""
}

type SaveResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7acdd0f2cbdcf63b, []int{1}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Item)(nil), "api.trac.cn.saveitem.Item")
	proto.RegisterType((*SaveResponse)(nil), "api.trac.cn.saveitem.SaveResponse")
}

func init() {
	proto.RegisterFile("services/itemsave/proto/item.proto", fileDescriptor_7acdd0f2cbdcf63b)
}

var fileDescriptor_7acdd0f2cbdcf63b = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x69, 0x37, 0x6d, 0x93, 0x49, 0x59, 0xc0, 0x2c, 0x60, 0x8a, 0x80, 0x92, 0x53, 0x4f,
	0x59, 0xd1, 0xee, 0x1b, 0xec, 0x29, 0x12, 0xe2, 0x50, 0x0a, 0xd7, 0xc8, 0xd8, 0x23, 0xb0, 0x94,
	0x3a, 0x96, 0xed, 0x76, 0xe9, 0x43, 0xf0, 0xce, 0x2b, 0x4f, 0xb2, 0x55, 0x0e, 0x3d, 0xc5, 0xff,
	0xf7, 0xcd, 0x28, 0x93, 0x78, 0xa0, 0xf0, 0xe8, 0x8e, 0x5a, 0xa2, 0xbf, 0xd5, 0x01, 0xf7, 0x5e,
	0x1c, 0xf1, 0xd6, 0xba, 0x36, 0xb4, 0x14, 0x4b, 0x3a, 0xb2, 0x1b, 0x61, 0x75, 0x19, 0x9c, 0x90,
	0xa5, 0x34, 0x65, 0x2c, 0x89, 0xae, 0xf8, 0x9f, 0x40, 0x52, 0x05, 0xdc, 0xb3, 0x8f, 0x00, 0x68,
	0xb5, 0x6f, 0x15, 0xd6, 0x5a, 0xf1, 0xd1, 0x72, 0xb4, 0x9a, 0x6c, 0xb3, 0x9e, 0x54, 0x2a, 0x6a,
	0xf9, 0x57, 0x18, 0x83, 0x4d, 0xd4, 0xe3, 0x4e, 0xf7, 0xa4, 0x52, 0xec, 0x3d, 0xa4, 0xca, 0x89,
	0xbd, 0x88, 0xf2, 0x8a, 0xe4, 0x8c, 0x72, 0xa5, 0xd8, 0x67, 0xc8, 0x3b, 0x15, 0x74, 0x68, 0x90,
	0x27, 0xcb, 0xd1, 0x2a, 0xdb, 0x02, 0xa1, 0x5d, 0x24, 0xec, 0x2d, 0x4c, 0x49, 0x7d, 0xe5, 0x13,
	0x72, 0x7d, 0x3a, 0xf3, 0x35, 0x9f, 0x0e, 0xf8, 0xfa, 0xcc, 0x37, 0x7c, 0x36, 0xe0, 0x9b, 0x33,
	0xbf, 0xe3, 0xe9, 0x80, 0xdf, 0xc5, 0x01, 0x9e, 0xbe, 0xec, 0xe0, 0x1a, 0x9e, 0x75, 0x03, 0xf4,
	0xe8, 0xa7, 0x6b, 0xd8, 0x02, 0x52, 0x75, 0x70, 0x22, 0xe8, 0xd6, 0x70, 0xa0, 0xe1, 0xcf, 0x99,
	0x7d, 0x81, 0xb9, 0x6c, 0x4d, 0x40, 0x13, 0xea, 0x70, 0xb2, 0xc8, 0x73, 0xea, 0xce, 0x7b, 0xb6,
	0x3b, 0x59, 0x64, 0x37, 0x30, 0xd1, 0x7b, 0xf1, 0x07, 0xf9, 0x9c, 0x5c, 0x17, 0xd8, 0x07, 0xc8,
	0xb4, 0xaf, 0xb5, 0x09, 0x42, 0x06, 0xfe, 0x9c, 0x4c, 0xaa, 0x7d, 0x45, 0x99, 0xbd, 0x81, 0xa9,
	0xf6, 0xb5, 0xc1, 0x07, 0x7e, 0xdd, 0xf7, 0xf8, 0xef, 0xf8, 0xd0, 0xe3, 0xa3, 0xb6, 0xfc, 0xc5,
	0x13, 0xfe, 0xa5, 0x6d, 0x9c, 0xc1, 0x36, 0xe2, 0x54, 0xcb, 0xf6, 0x60, 0x02, 0x3a, 0xfe, 0x72,
	0x39, 0x5a, 0x5d, 0x6d, 0xf3, 0xc8, 0xee, 0x3b, 0xc4, 0xae, 0x61, 0x1c, 0x3c, 0x7f, 0x45, 0x5d,
	0xe3, 0xe0, 0xd9, 0x3b, 0x98, 0x19, 0xfc, 0x17, 0xe2, 0x75, 0xb0, 0xee, 0x67, 0xc4, 0x58, 0x29,
	0xf6, 0x09, 0x72, 0xef, 0x64, 0x2d, 0x1b, 0x6d, 0xa3, 0x7c, 0x4d, 0x32, 0xf3, 0x4e, 0xde, 0x37,
	0xda, 0x56, 0xaa, 0x28, 0x60, 0xfe, 0x43, 0x1c, 0x71, 0x8b, 0xde, 0xb6, 0xc6, 0x23, 0x63, 0x90,
	0xc8, 0x56, 0x61, 0xbf, 0x10, 0x74, 0x5e, 0xef, 0x20, 0x89, 0x35, 0xec, 0x1b, 0xa4, 0xf1, 0x49,
	0xeb, 0xb3, 0x28, 0x2f, 0xad, 0x57, 0x19, 0xdd, 0xa2, 0xb8, 0xec, 0x86, 0xef, 0x29, 0x9e, 0xfd,
	0x9e, 0xd2, 0x9a, 0x6e, 0x1e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x76, 0xd7, 0xb2, 0xcc, 0x02,
	0x00, 0x00,
}
