// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-05-07 03:35:43.171004 +0800 CST m=+0.053143042

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/spider": {
            "post": {
                "description": "insert episode",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Spider"
                ],
                "summary": "Insert episode from URL of MGTV",
                "operationId": "insert episode",
                "parameters": [
                    {
                        "description": "Name",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.SpiderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app.SpiderResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/app.SpiderResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.SpiderRequest": {
            "type": "object",
            "required": [
                "channel_id",
                "url"
            ],
            "properties": {
                "channel_id": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "app.SpiderResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Mgtv"
                    }
                },
                "error": {
                    "type": "object"
                },
                "length": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "model.Mgtv": {
            "type": "object",
            "properties": {
                "channel_id": {
                    "type": "integer"
                },
                "content_type": {
                    "type": "string"
                },
                "drama_id": {
                    "type": "integer"
                },
                "drama_title": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "episode_id": {
                    "type": "integer"
                },
                "episode_url": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "is_intact": {
                    "type": "string"
                },
                "is_new": {
                    "type": "string"
                },
                "is_vip": {
                    "type": "string"
                },
                "next_id": {
                    "type": "string"
                },
                "play_counter": {
                    "type": "integer"
                },
                "src_clip_id": {
                    "type": "string"
                },
                "title1": {
                    "type": "string"
                },
                "title2": {
                    "type": "string"
                },
                "title3": {
                    "type": "string"
                },
                "title4": {
                    "type": "string"
                },
                "ts": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
